spring:
#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: your_name # логин от учётки Yandex
#    password: your_password # специальный пароль для приложения
#    test-connection: true # проверка подключения при старте приложения
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#    sender: # отправитель письма (его почта и имя)
#      email: your_name@yandex.ru
#      text: no-reply
  datasource:
    url: jdbc:postgresql://localhost:5432/avito
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m

