spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_start
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m

